### ISSUE TITLE
library name

### ISSUE THREAD

**Issue by bioinfornatics** [ahupp/python-magic#33] opened 2013-05-31 13:19 UTC
Dear,
I am a fedora packager and i am interested to package it.

The problem that is
- `python-magic` package name is already taken
- `magic` namespace is already taken too

Could you set another name like `python-libmagic` and `libmagic` as namespace?

**Comment by AbdealiJK** [comment] 2016-05-08 04:03
I'd really like this to be a debian/fedora package too.
I've been using this package from pypi until now - and it would be great to have a system package for it.
Please considering claiming a namespace like `python-magic-lib` or so (Although I agree python-magic is a more appropriate name)

**Comment by bioinfornatics** [comment] 2016-06-02 14:28
Is funny to see that developper do not trust our works ....
while I report it 3 years later

**Comment by sebix** [comment] 2016-10-12 13:16
This issue is a duplicate of #21 

Unfortunately this hasn't been resolved yet. Also looking forward for a solution.

**Comment by mbehrle** [comment] 2017-09-05 10:42
Just adding emphasize and interest on this very problem as Debian packager. 

This is defintely a show-stopper for packages using this library to enter into Debian. Either they have to be patched to use file-magic or we will have to patch/fork this library to use a different namespace.

Best solution of course would be to merge the two libraries and thus avoid the namespace conflict.
Could anyone, probably best https://github.com/ahupp please comment or put a little summary or hint, what has been done to  merge the two libraries and why the two projects can't  get together to find a useful solution for all?
Unfortunately the list server at http://mx.gw.com[1] is down, where I possibly could find more information.

Thanks for all your input,
Mathias

[1] http://mx.gw.com/pipermail/file/2016/002174.html

**Comment by sebix** [comment] 2017-09-05 16:44
Just for clarity: I have the same problem for openSUSE

**Comment by ahupp** [comment] 2018-01-15 07:47
I have a test branch that includes both the "normal" python-magic interface as well as the libmagic python interface.  

https://github.com/ahupp/python-magic/tree/libmagic-compat

I'd like a few people to try it out before I push it to pypy, anyone interested?

**Comment by ahupp** [comment] 2018-08-20 00:51
Sorry this has dragged on so long.  Im going to close this as a dupe of #21.  I have the change all queued up, and have just reached out to he libmagic upstream folks about it.  Unless they have some strong objections I'll merge the libmagic-compat branch next wee.

**Closed by ahupp** 2018-08-20 00:51 UTC
